name: electron

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build Electron app
        run: | 
          npm install
          npm run make

      - name: list
        run: Get-ChildItem -Path ./out/ –Recurse
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
           name: uds-${{matrix.os}}
           path: | 
              ./out/make/zip/darwin/x64/
              ./out/make/zip/windows/x64/

      

      

